$("document").ready(function(){
	$("#accueil").hide()
	$("#jardinerie").hide()
	$("#lombricompost").hide()
	$("#tableau").hide()
	$("#accueil").hide()
	$(".aside").hide()
	$(".asideImage").hide()
	$(".aside").show(2000)
	$(".asideImage").show(2000)
	$("#accueil").show(2000)
	$("#jardinerie").show(3000)
	$("#lombricompost").show(3000)
	$("#tableau").show(4000)

})	